services:
  postgres-mind-castle-gql:
    image: postgres:14.2
    container_name: mind-castle-db-gql
    env_file:
      - .env
    environment:
      POSTGRES_DB: mind-castle-gql
    volumes:
      - mind_catle_gql_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: mind-castle-gql-backend
    ports:
      - "8000:8000"
    depends_on:
      postgres-mind-castle-gql:
          condition: service_started
          restart: true

    env_file:
      - ./.env.local
    volumes:
      - ./:/app

volumes:
  mind_catle_gql_data:
  